#!/bin/bash

# Read configuration from stdin (JSON format from Start9)
export CONFIG_JSON=$(cat)

# Use Python for proper JSON parsing (read from environment variable)
python3 <<'PYTHON_SCRIPT'
import json
import sys
import os

try:
    config = json.loads(os.environ['CONFIG_JSON'])
    
    # Extract values with defaults (keys are kebab-case from config spec)
    mock_mode = str(config.get('mock-mode', True)).lower() == 'true'
    bitcoin_rpc_user = config.get('bitcoin-rpc-user', '')
    bitcoin_rpc_password = config.get('bitcoin-rpc-password', '')
    mempool_api_url = config.get('mempool-api-url', 'https://mempool.local')
    alert_drop_pct = config.get('alert-drop-pct', 0.2)
    alert_window_days = config.get('alert-window-days', 14)
    t_min_secs = config.get('t-min-secs', 1000)
    mu_min_sats_per_s = config.get('mu-min-sats-per-s', 0.000001)
    pipeline_interval_seconds = config.get('pipeline-interval-seconds', 600)
    
    # Determine Bitcoin RPC URL from dependency
    # If dependencies are available, use them; otherwise use defaults
    # Start9 uses service name format: <package-id>.embassy
    bitcoin_rpc_url = 'http://bitcoind.embassy:8332'
    
    # If pointers are empty, dependencies might not be connected
    # In that case, use mock mode or user-provided values
    
    # Write .env file
    env_content = f"""# Bitcoin Seconds Configuration
# Generated by Start9 (do not edit manually)

MOCK_MODE={'true' if mock_mode else 'false'}
ALERT_DROP_PCT={alert_drop_pct}
ALERT_WINDOW_DAYS={alert_window_days}
T_MIN_SECS={t_min_secs}
MU_MIN_SATS_PER_S={mu_min_sats_per_s}
PIPELINE_INTERVAL_SECONDS={pipeline_interval_seconds}
API_PORT=8080
DB_PATH=/app/data/bxs.sqlite
"""
    
    # Add Bitcoin RPC config if not in mock mode
    if not mock_mode and bitcoin_rpc_user and bitcoin_rpc_password:
        env_content += f"""
# Bitcoin RPC Configuration (from dependency)
BITCOIN_RPC_URL={bitcoin_rpc_url}
BITCOIN_RPC_USER={bitcoin_rpc_user}
BITCOIN_RPC_PASSWORD={bitcoin_rpc_password}
"""
    
    # Add Mempool config if not in mock mode
    if not mock_mode and mempool_api_url:
        env_content += f"""
# Mempool.space API (from dependency)
MEMPOOL_API_URL={mempool_api_url}
"""
    
    # Write to .env file
    with open('/app/.env', 'w') as f:
        f.write(env_content)
    
    # Output JSON response for Start9
    result = {
        "success": True,
        "message": "Configuration updated successfully"
    }
    print(json.dumps(result))
    
except Exception as e:
    # Output error as JSON
    result = {
        "success": False,
        "error": str(e)
    }
    print(json.dumps(result), file=sys.stderr)
    sys.exit(1)
PYTHON_SCRIPT

